load_task:
  description: >
    Load and read the data from the input file.
    Make sure you organize it in a manner that can be processed by other agents 
    and tasks to analyze the data.
  expected_output: >
    The input data in a fromat that can be analyzed by further agents and tasks.
  agent: loader

analyzer_task:
  description: >
    Conduct a thorough research about webserver event logs provided by the loader agent.
    Make sure you find any anomnalies and other interesting and relevant information from a 
    cybersecurity point of view.
  expected_output: >
    A list with statistical data of the most relevant information about the webserver event logs.
  agent: analyzer

reporting_task:
  description: >
    Review the context you got and expand each topic into a full section for a report.
    Make sure the report is detailed and contains any and all relevant information.
  expected_output: >
    A fully fledge reports with the mains topics, each with a full section of information.
    Formatted as markdown without '```'.
  agent: reporting_analyst
  context: [analyzer_task]